docs(metadata-service): refine data model
dasch-swiss/dasch-service-platform pull request #18
Opened 2021-03-15 20:49 UTC by BalduinLandolt

resolves BS-41

Refine data model, create a json schema and UML diagram

2021-03-29 12:44 UTC, subotic commented
@BalduinLandolt here are my answers to the questions in the datamodel.md and also some comments (in no particular order):

As a general remark, I like to model everything as loosely coupled as possible. There are only two types of values, either value objects or instances of classes. If it has more than one property or it has a chance to be extended in the future, then it is a class.

- Class: Grant: is missing `id` and `type`. I see grant as a separate thing.

2021-04-09 07:48 UTC, BalduinLandolt commented
@subotic @mpro7 not much has changed since last review. But I think it's finalized now.

2021-04-09 09:04 UTC, mpro7 requested changes

2021-04-09 09:04 UTC, mpro7 commented on docs/services/metadata/example.json
> +{
Do we need this file anymore if there is `api-example.puml` which I think is 1:1 with this one?

2021-04-09 10:22 UTC, BalduinLandolt commented on docs/services/metadata/datamodel.md
> +The json representation is "flat", i.e. not nested, so all top-level types are present in the first level of depth of the json document tree. All those objects have a unique `@id` property. Wherever
I don't think so, but I could be wrong

2021-04-09 10:22 UTC, BalduinLandolt commented on docs/services/metadata/datamodel.md
> +The overall structure of the json representation of a metadata-set should look like this:
you're right

2021-04-09 10:25 UTC, mpro7 commented on docs/services/metadata/datamodel.md
> +The json representation is "flat", i.e. not nested, so all top-level types are present in the first level of depth of the json document tree. All those objects have a unique `@id` property. Wherever
I'm sorry for my poor English 👀 , you're right.

2021-04-09 10:27 UTC, BalduinLandolt commented on docs/services/metadata/datamodel.md
> +The json representation is "flat", i.e. not nested, so all top-level types are present in the first level of depth of the json document tree. All those objects have a unique `@id` property. Wherever
all good! :)

2021-04-09 14:08 UTC, BalduinLandolt commented on docs/services/metadata/api-example.puml
> +    ],
done, renamed to `text`

2021-04-12 07:58 UTC, mpro7 approved these changes
Thanks!

2021-04-12 08:01 UTC, merged